app_logging_level: INFO
gpu_monitoring_interval: 10
environment_name: dev
handlers:
  - type: file
    config:
      file_prefix: gpu_monitor
      rotate: 1000
      name: gpu_monitor
      gzip: true
  - type: console
    config:
      name: gpu_monitor
  - type: mongo
    config:
      mongo_host: localhost
      mongo_db: gpu_monitor
      mongo_collection: gpu_monitor_0
      node_id: 0
